//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetierGestionStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvisionnement
    {
        public int idApp { get; set; }
        public double qteProd { get; set; }
        public int idProduit { get; set; }
        public System.DateTime datePeremption { get; set; }
        public System.DateTime dateApp { get; set; }
    }
}
