//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetierGestionStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int ID { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public double Quantite { get; set; }
        public double QuantiteMin { get; set; }
        public double Prix { get; set; }
        public int cat_id { get; set; }
    }
}
