//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetierGestionStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int ID { get; set; }
        public int CodeProduit { get; set; }
        public string nomProduit { get; set; }
        public System.DateTime DateStockage { get; set; }
        public double Quantite { get; set; }
        public string status { get; set; }
    }
}
